--oracle
alter table F_DATACATALOG add CREATOR VARCHAR2(32);
alter table F_DATACATALOG add UPDATOR VARCHAR2(32);
alter table F_DATACATALOG RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_OPTDEF add CREATOR VARCHAR2(32);
alter table F_OPTDEF add UPDATOR VARCHAR2(32);
alter table F_OPTDEF RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_OPTINFO add CREATOR VARCHAR2(32);
alter table F_OPTINFO add UPDATOR VARCHAR2(32);
alter table F_OPTINFO RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_ROLEPOWER add CREATOR VARCHAR2(32);
alter table F_ROLEPOWER add UPDATOR VARCHAR2(32);
alter table F_ROLEPOWER RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_USERROLE add CREATOR VARCHAR2(32);
alter table F_USERROLE add UPDATOR VARCHAR2(32);
alter table F_USERROLE RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_USERUNIT add CREATOR VARCHAR2(32);
alter table F_USERUNIT add UPDATOR VARCHAR2(32);
alter table F_USERUNIT RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;


--mysql

alter table F_DATACATALOG add CREATOR VARCHAR(32);
alter table F_DATACATALOG add UPDATOR VARCHAR(32);
alter table F_DATACATALOG change  LASTMODIFYDATE UPDATEDATE date;

alter table F_OPTDEF add CREATOR VARCHAR(32);
alter table F_OPTDEF add UPDATOR VARCHAR(32);
alter table F_OPTDEF change  LASTMODIFYDATE UPDATEDATE date;

alter table F_OPTINFO add CREATOR VARCHAR(32);
alter table F_OPTINFO add UPDATOR VARCHAR(32);
alter table F_OPTINFO change  LASTMODIFYDATE UPDATEDATE date;

alter table F_ROLEPOWER add CREATOR VARCHAR(32);
alter table F_ROLEPOWER add UPDATOR VARCHAR(32);
alter table F_ROLEPOWER change  LASTMODIFYDATE UPDATEDATE date;

alter table F_USERROLE add CREATOR VARCHAR(32);
alter table F_USERROLE add UPDATOR VARCHAR(32);
alter table F_USERROLE change  LASTMODIFYDATE UPDATEDATE date;

alter table F_USERUNIT add CREATOR VARCHAR(32);
alter table F_USERUNIT add UPDATOR VARCHAR(32);
alter table F_USERUNIT change  LASTMODIFYDATE UPDATEDATE date;