CREATE TABLE SPRING_SESSION (
	TOKEN_NO CHAR(48) NOT NULL,
	CREATION_TIME NUMBER(19,0) NOT NULL,
	LAST_ACCESS_TIME NUMBER(19,0) NOT NULL,
	MAX_INACTIVE_INTERVAL NUMBER(10,0) NOT NULL,
	USER_CODE VARCHAR2(50 CHAR),
	USER_DETAILS BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (TOKEN_NO)
);

CREATE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (LAST_ACCESS_TIME);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (USER_CODE);
