--oracle
alter table F_UNITINFO add CREATOR VARCHAR2(32);
alter table F_UNITINFO add UPDATOR VARCHAR2(32);
alter table F_UNITINFO RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_ROLEINFO add CREATOR VARCHAR2(32);
alter table F_ROLEINFO add UPDATOR VARCHAR2(32);
alter table F_ROLEINFO RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;

alter table F_USERINFO add CREATOR VARCHAR2(32);
alter table F_USERINFO add UPDATOR VARCHAR2(32);
alter table F_USERINFO RENAME COLUMN  LASTMODIFYDATE TO UPDATEDATE;


--mysql

alter table F_UNITINFO add CREATOR VARCHAR(32);
alter table F_UNITINFO add UPDATOR VARCHAR(32);
alter table F_UNITINFO change  LASTMODIFYDATE UPDATEDATE date;

alter table F_ROLEINFO add CREATOR VARCHAR(32);
alter table F_ROLEINFO add UPDATOR VARCHAR(32);
alter table F_ROLEINFO change  LASTMODIFYDATE UPDATEDATE date;

alter table F_USERINFO add CREATOR VARCHAR(32);
alter table F_USERINFO add UPDATOR VARCHAR(32);
alter table F_USERINFO change  LASTMODIFYDATE UPDATEDATE date;