CREATE TABLE SPRING_SESSION (
	TOKEN_NO CHAR(48) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	USER_CODE VARCHAR(50) NOT NULL,
	USER_DETAILS LONGVARBINARY NOT NULL,
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (TOKEN_NO)
);

CREATE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (LAST_ACCESS_TIME);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (USER_CODE);
